services:
  db:
    image: postgres:15
    container_name: nossa_faculdade_db
    environment:
      POSTGRES_USER: nossa_faculdade
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: nossa_faculdade
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nossa_faculdade_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://nossa_faculdade:senha_segura@db:5432/nossa_faculdade?schema=public"

volumes:
  pg_data: